basket/urls.py
from tkinter.font import names
from django.urls import path

from . import views
app_name='basket'

urlpatterns = [
    path('',views.basket_summary,name='basket_summary'),
    path('add/',views.basket_add,name='basket_add')
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='store')),
    path('basket/',include('basket.urls',namespace='basket')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

store/urls.py
from django.urls import path

from . import views

app_name="store"

urlpatterns = [
     path('',views.all_products,name='all_products'),
     path('item/<slug:slug>/',views.product_detail,name="product_detail"),
     path('search/<slug:category_slug>/',views.category_list,name="category_list"),
 ]
  

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from tabnanny import verbose
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager,self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name=models.CharField(max_length=255,db_index=True)
    slug=models.SlugField(max_length=255,unique=True)

    class Meta:
        verbose_name_plural="categories"

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])
    

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category=models.ForeignKey(Category,related_name='product',on_delete=models.CASCADE)
    created_by=models.ForeignKey(User,on_delete=models.CASCADE,related_name='product_crator')
    title=models.CharField(max_length=255)
    author=models.CharField(max_length=255,default='admin')
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='images/')
    slug=models.SlugField(max_length=255,null=True)
    price=models.DecimalField(max_digits=7,decimal_places=3,null=True)
    in_stock=models.BooleanField(default=True)
    is_active=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    objects=models.Manager()
    products=ProductManager()

    class Meta:
        verbose_name_plural='Products'
        ordering=('created',)

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])
    

    def __str__(self):
        return self.title

     

basket/views.py
from urllib import response
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from store.models import Product
from .basket import Basket
def basket_summary(request):
    return render(request,'store/basket/summary.html')

def basket_add(request):
    
    basket=Basket(request)
    if request.POST.get('action')=='post':
        product_id=int(request.POST.get('productid'))
        product_qty=int(request.POST.get('productqty'))
        product=get_object_or_404(Product,id=product_id)
        basket.add(product=product,qty=product_qty)
        response = JsonResponse({'qty':'product_qty'})
        return response

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category,Product


def all_products(request):
     products=Product.products.all()
     return render(request,'store/home.html',{'products':products})

def product_detail(request,slug):
     product=get_object_or_404(Product,slug=slug,in_stock=True)
     return render(request,'store/products/detail.html',{"product":product})

def category_list(request,category_slug):
     category=get_object_or_404(Category,slug=category_slug)
     products=Product.objects.filter(category=category)
     return render(request,'store/products/category.html',{"category":category,"products" :products})

templates/store/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">

  <meta name="description" content="xz">
  <meta name="author" content="xz">

  <title>ECOMMERCE SHOP</title>


  <!-- Bootstrap core CSS -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
  </script>
</head>

<body>
  <header>

    <div class="nav-link drodown-toggle">
      <a class="navbar-brand" href="/">Digix Store</a>
      </a>
      <nav class="navbar navbar-light bg-light">
        <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </nav>

      <a type="button" role="button" href="{% url "basket:basket_summary"%}" class="btn btn-secondary">
        <div id='basket-qty' class="d-inline-flex">1</div>
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart"
          viewBox="0 0 16 16">
          <path
            d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </svg>
        Card
      </a>

      {% comment %} <il class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          libary
        </a> {% endcomment %}
        <ul class="drodown-menu" aria-labelledby="navbarDropdown">

          <li><a class="dropdown-item" href="{%url "store:all_products"%}">All</a></li>

          {%for c in categories %}

          <li{%if category.slug == c.slug%}class="selected"{%endif%}>
      </il>
      <a class="dropdown-item" href="{{c.get_absolute_url}}">{{c.name|title}}</a>
      </li>

      {% endfor %}
      </ul>
      </il>

      {% comment %} <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Features</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Enterprise</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="#">Support</a>
        <a class="py-2 text-dark text-decoration-none" href="#">Pricing</a>
      </nav>
    </div> {% endcomment %}

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Digix</h1>
      <p class="fs-5 text-muted">Store</p>
    </div>
  </header>
  <div id="content">{%block content%}{%endblock%}</div>

</body>

</html>

templates/store/basket/summary.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Basket{% endblock  %}
{%block content%}

    Basket page
{%endblock%}

templates/store/home.html
{% extends './base.html' %}
{% load static %}
{% block title %}Home{% endblock  %}

{% block content %}
<main>

    <section class="py-5 text-center container">
      <div class="row py-lg-3">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">All Products</h1>
          <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
          <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
          </p>
        </div>
      </div>
    </section>
    <div class="pb-3 h5">All Products</div>
    <div class="album py-5 bg-light">
      <div class="container">
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {%for product in products%}
          <div class="col">
            <div class="card shadow-sm">
                <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}"    

              
  
              <div class="card-body">
                <p class="card-text">
                    <a class="text-dark text-decoration-nine" href="{{product.get_absolute_url}}">{{product.title}}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          {%endfor%}
          
         
                  
         
  
  </main>


{% endblock  %}

templates/store/products/category.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Home{% endblock  %}

{% block content %}
<main>

   
    <div class="pb-3 h5">{{category.name|title}}</div>
    <div class="album py-5 bg-light">
      <div class="container">
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {%for product in products%}
          <div class="col">
            <div class="card shadow-sm">
                <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}"    

              
  
              <div class="card-body">
                <p class="card-text">
                    <a class="text-dark text-decoration-nine" href="{{product.get_absolute_url}}">{{product.title}}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  
                  
                  <small class="text-muted">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          {%endfor%}        
         
                  
         
  
  </main>


{% endblock  %}

templates/store/products/detail.html
{%extends "../base.html"%}

{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">تومان{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end"><button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">اضافه کردن به سبد خرید</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>
<script>
    $(document).on('click','#add-button',function(e){
        e.preventDefult();
        
        $.ajax({
            type:'POST',
            url:'{% url "basket:basket_add"%}',
            data:{
                productid:$('#add-button').val().,
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken:"{% csrf_token %}",
                action:'post'
            },
            success:function(jason){
                document.getElementById('basket-qty').innerHTML = json.qty
            },
            error:function(xhr,errmsg,err){}

        });
    })
</script>
{% endblock %}